### ISSUE TITLE
Искажение изображений при выставлении ширины

### ISSUE THREAD

**Issue by lamaster** [ReginaUtsika/Project03#2]
<img width="1385" alt="Screenshot 2020-09-28 at 16 05 13" src="https://user-images.githubusercontent.com/175121/94436016-94582100-01a4-11eb-8485-c6bd59aa5fe1.png">
<img width="1433" alt="Screenshot 2020-09-28 at 16 04 28" src="https://user-images.githubusercontent.com/175121/94436029-98843e80-01a4-11eb-9f92-2d773780ec93.png">

**Comment by Ginnovich** [comment]
https://github.com/ReginaUtsika/Project03/commit/befcc522bf241104a5a981ff68e840b597790d9b
